/*
* 本文件用于存放宝可梦公用数据列表
* 包含：属性、地区、特性
* 后期优化成使用请求获取
* 
*/

//类型声明
type AbilityArray = {
    label: string;
    value: string;
}[];
type TypeArray = {
    label: string;
    value: string;
}[];
type RegionArray = {
    label: string;
    value: string;
}[];

//特性
export const abilityArray: AbilityArray = [
    { label: "所有", value: "" },
    { label: "适应力", value: "adaptability" },
    { label: "飞行皮肤", value: "aerilate" },
    { label: "引爆", value: "aftermath" },
    { label: "气闸", value: "air lock" },
    { label: "愤怒穴位", value: "anger point" },
    { label: "危险预知", value: "anticipation" },
    { label: "沙穴", value: "arena trap" },
    { label: "芳香幕", value: "aroma veil" },
    { label: "气场破坏", value: "aura break" },
    { label: "梦魇", value: "bad dreams" },
    { label: "蓄电池", value: "battery" },
    { label: "战斗盔甲", value: "battle armor" },
    { label: "异兽提升", value: "beast boost" },
    { label: "怒火冲天", value: "berserk" },
    { label: "健壮胸肌", value: "big pecks" },
    { label: "猛火", value: "blaze" },
    { label: "防弹", value: "bulletproof" },
    { label: "颊囊", value: "cheek pouch" },
    { label: "叶绿素", value: "chlorophyll" },
    { label: "恒净之躯", value: "clear body" },
    { label: "无关天气", value: "cloud nine" },
    { label: "变色", value: "color change" },
    { label: "绝对睡眠", value: "comatose" },
    { label: "好胜", value: "competitive" },
    { label: "复眼", value: "compound eyes" },
    { label: "唱反调", value: "contrary" },
    { label: "腐蚀", value: "corrosion" },
    { label: "诅咒之躯", value: "cursed body" },
    { label: "迷人之躯", value: "cute charm" },
    { label: "湿气", value: "damp" },
    { label: "舞者", value: "dancer" },
    { label: "暗黑气场", value: "dark aura" },
    { label: "鲜艳之躯", value: "dazzling" },
    { label: "软弱", value: "defeatist" },
    { label: "不服输", value: "defiant" },
    { label: "德尔塔气", value: "delta stream" },
    { label: "终结之地", value: "desolate land" },
    { label: "画皮", value: "disguise" },
    { label: "下载", value: "download" },
    { label: "降雨", value: "drizzle" },
    { label: "日照", value: "drought" },
    { label: "干燥皮肤", value: "dry skin" },
    { label: "早起", value: "early bird" },
    { label: "孢子", value: "effect spore" },
    { label: "电气制造", value: "electric surge" },
    { label: "危险回避", value: "emergency exit" },
    { label: "妖精气场", value: "fairy aura" },
    { label: "过滤", value: "filter" },
    { label: "火焰之躯", value: "flame body" },
    { label: "引火", value: "flash fire" },
    { label: "花之礼", value: "flower gift" },
    { label: "花幕", value: "flower veil" },
    { label: "毛茸茸", value: "fluffy" },
    { label: "阴晴不定", value: "forecast" },
    { label: "预知梦", value: "forewarn" },
    { label: "友情防守", value: "friend guard" },
    { label: "察觉", value: "frisk" },
    { label: "金属防护", value: "full metal body" },
    { label: "毛皮大衣", value: "fur coat" },
    { label: "贪吃鬼", value: "gluttony" },
    { label: "黏滑", value: "gooey" },
    { label: "青草制造", value: "grassy surge" },
    { label: "毅力", value: "guts" },
    { label: "治愈之心", value: "healer" },
    { label: "耐热", value: "heatproof" },
    { label: "重金属", value: "heavy metal" },
    { label: "采蜜", value: "honey gather" },
    { label: "大力士", value: "huge power" },
    { label: "活力", value: "hustle" },
    { label: "湿润之躯", value: "hydration" },
    { label: "怪力钳", value: "hyper cutter" },
    { label: "冰冻之躯", value: "ice body" },
    { label: "发光", value: "illuminate" },
    { label: "幻觉", value: "illusion" },
    { label: "免疫", value: "immunity" },
    { label: "穿透", value: "infiltrator" },
    { label: "飞出的内", value: "innards out" },
    { label: "精神力", value: "inner focus" },
    { label: "不眠", value: "insomnia" },
    { label: "威吓", value: "intimidate" },
    { label: "铁刺", value: "iron barbs" },
    { label: "铁拳", value: "iron fist" },
    { label: "正义之心", value: "justified" },
    { label: "锐利目光", value: "keen eye" },
    { label: "笨拙", value: "klutz" },
    { label: "叶子防守", value: "leaf guard" },
    { label: "飘浮", value: "levitate" },
    { label: "轻金属", value: "light metal" },
    { label: "避雷针", value: "lightning rod" },
    { label: "柔软", value: "limber" },
    { label: "污泥浆", value: "liquid ooze" },
    { label: "魔法镜", value: "magic bounce" },
    { label: "魔法防守", value: "magic guard" },
    { label: "魔术师", value: "magician" },
    { label: "熔岩铠甲", value: "magma armor" },
    { label: "磁力", value: "magnet pull" },
    { label: "神奇鳞片", value: "marvel scale" },
    { label: "超级发射", value: "mega launcher" },
    { label: "不仁不义", value: "merciless" },
    { label: "负电", value: "minus" },
    { label: "薄雾制造", value: "misty surge" },
    { label: "破格", value: "mold breaker" },
    { label: "电气引擎", value: "motor drive" },
    { label: "自信过度", value: "moxie" },
    { label: "多属性", value: "multitype" },
    { label: "木乃伊", value: "mummy" },
    { label: "自然回复", value: "natural cure" },
    { label: "脑核之力", value: "neuroforce" },
    { label: "无防守", value: "no guard" },
    { label: "一般皮肤", value: "normalize" },
    { label: "迟钝", value: "oblivious" },
    { label: "防尘", value: "overcoat" },
    { label: "茂盛", value: "overgrow" },
    { label: "我行我素", value: "own tempo" },
    { label: "亲子爱", value: "parental bond" },
    { label: "顺手牵羊", value: "pickpocket" },
    { label: "捡拾", value: "pickup" },
    { label: "妖精皮肤", value: "pixilate" },
    { label: "正电", value: "plus" },
    { label: "毒疗", value: "poison heal" },
    { label: "毒刺", value: "poison point" },
    { label: "毒手", value: "poison touch" },
    { label: "群聚变形", value: "power construct" },
    { label: "恶作剧之", value: "prankster" },
    { label: "压迫感", value: "pressure" },
    { label: "始源之海", value: "primordial sea" },
    { label: "棱镜装甲", value: "prism armor" },
    { label: "精神制造", value: "psychic surge" },
    { label: "瑜伽之力", value: "pure power" },
    { label: "女王的威", value: "queenly majesty" },
    { label: "飞毛腿", value: "quick feet" },
    { label: "雨盘", value: "rain dish" },
    { label: "胆怯", value: "rattled" },
    { label: "接球手", value: "receiver" },
    { label: "舍身", value: "reckless" },
    { label: "冰冻皮肤", value: "refrigerate" },
    { label: "再生力", value: "regenerator" },
    { label: "斗争心", value: "rivalry" },
    { label: "ＡＲ系统", value: "rks system" },
    { label: "坚硬脑袋", value: "rock head" },
    { label: "粗糙皮肤", value: "rough skin" },
    { label: "逃跑", value: "run away" },
    { label: "沙之力", value: "sand force" },
    { label: "拨沙", value: "sand rush" },
    { label: "扬沙", value: "sand stream" },
    { label: "沙隐", value: "sand veil" },
    { label: "食草", value: "sap sipper" },
    { label: "鱼群", value: "schooling" },
    { label: "胆量", value: "scrappy" },
    { label: "天恩", value: "serene grace" },
    { label: "幻影防守", value: "shadow shield" },
    { label: "踩影", value: "shadow tag" },
    { label: "蜕皮", value: "shed skin" },
    { label: "强行", value: "sheer force" },
    { label: "硬壳盔甲", value: "shell armor" },
    { label: "鳞粉", value: "shield dust" },
    { label: "界限盾壳", value: "shields down" },
    { label: "单纯", value: "simple" },
    { label: "连续攻击", value: "skill link" },
    { label: "慢启动", value: "slow start" },
    { label: "拨雪", value: "slush rush" },
    { label: "狙击手", value: "sniper" },
    { label: "雪隐", value: "snow cloak" },
    { label: "降雪", value: "snow warning" },
    { label: "太阳之力", value: "solar power" },
    { label: "坚硬岩石", value: "solid rock" },
    { label: "魂心", value: "soul-heart" },
    { label: "隔音", value: "soundproof" },
    { label: "加速", value: "speed boost" },
    { label: "蹲守", value: "stakeout" },
    { label: "慢出", value: "stall" },
    { label: "持久力", value: "stamina" },
    { label: "战斗切换", value: "stance change" },
    { label: "静电", value: "static" },
    { label: "不屈之心", value: "steadfast" },
    { label: "钢能力者", value: "steelworker" },
    { label: "恶臭", value: "stench" },
    { label: "黏着", value: "sticky hold" },
    { label: "引水", value: "storm drain" },
    { label: "强壮之颚", value: "strong jaw" },
    { label: "结实", value: "sturdy" },
    { label: "吸盘", value: "suction cups" },
    { label: "超幸运", value: "super luck" },
    { label: "冲浪之尾", value: "surge surfer" },
    { label: "虫之预感", value: "swarm" },
    { label: "甜幕", value: "sweet veil" },
    { label: "悠游自如", value: "swift swim" },
    { label: "同步", value: "synchronize" },
    { label: "蹒跚", value: "tangled feet" },
    { label: "卷发", value: "tangling hair" },
    { label: "技术高手", value: "technician" },
    { label: "心灵感应", value: "telepathy" },
    { label: "兆级电压", value: "teravolt" },
    { label: "厚脂肪", value: "thick fat" },
    { label: "有色眼镜", value: "tinted lens" },
    { label: "激流", value: "torrent" },
    { label: "硬爪", value: "tough claws" },
    { label: "复制", value: "trace" },
    { label: "先行治疗", value: "triage" },
    { label: "懒惰", value: "truant" },
    { label: "涡轮火焰", value: "turboblaze" },
    { label: "纯朴", value: "unaware" },
    { label: "轻装", value: "unburden" },
    { label: "紧张感", value: "unnerve" },
    { label: "胜利之星", value: "victory star" },
    { label: "干劲", value: "vital spirit" },
    { label: "蓄电", value: "volt absorb" },
    { label: "储水", value: "water absorb" },
    { label: "水泡", value: "water bubble" },
    { label: "遇水凝固", value: "water compaction" },
    { label: "水幕", value: "water veil" },
    { label: "碎裂铠甲", value: "weak armor" },
    { label: "白色烟雾", value: "white smoke" },
    { label: "跃跃欲逃", value: "wimp out" },
    { label: "神奇守护", value: "wonder guard" },
    { label: "奇迹皮肤", value: "wonder skin" },
    { label: "捡球", value: "ball fetch" },
    { label: "除障", value: "screen cleaner" },
    { label: "蒸汽机", value: "steam engine" },
    { label: "一猩一意", value: "gorilla tactics" },
    { label: "不挠之剑", value: "intrepid sword" },
    { label: "不屈之盾", value: "dauntless shield" },
    { label: "棉絮", value: "cotton down" },
    { label: "一口导弹", value: "gulp missile" },
    { label: "庞克摇滚", value: "punk rock" },
    { label: "吐沙", value: "sand spit" },
    { label: "熟成", value: "ripen" },
    { label: "结冻头", value: "ice face" },
    { label: "能量点", value: "power spot" },
    { label: "拟态", value: "mimicry" },
    { label: "化学变化", value: "neutralizing gas" },
    { label: "粉彩护幕", value: "pastel veil" },
    { label: "饱了又饿", value: "hunger switch" },
    { label: "游魂", value: "wandering spirit" },
    { label: "无形拳", value: "unseen fist" },
    { label: "电晶体", value: "transistor" },
    { label: "龙颚", value: "dragon's maw" },
    { label: "苍白嘶鸣", value: "chilling neigh" },
    { label: "漆黑嘶鸣", value: "grim neigh" },
    { label: "人马一体", value: "as one" },
    { label: "速击", value: "quick draw" },
    { label: "怪药", value: "curious medicine" },
    { label: "跟风", value: "opportunist" },
    { label: "反刍", value: "cud chew" },
    { label: "全能变身", value: "zero to hero" },
    { label: "掉出种子", value: "seed sower" },
    { label: "电力转换", value: "electromorphosis" },
    { label: "食土", value: "earth eater" },
    { label: "热交换", value: "thermal exchange" },
    { label: "发号施令", value: "commander" },
    { label: "风力发电", value: "wind power" },
    { label: "愤怒甲壳", value: "anger shell" },
    { label: "洁净之盐", value: "purifying salt" },
    { label: "毒满地", value: "toxic debris" },
    { label: "焦香之躯", value: "well-baked body" },
    { label: "乘风", value: "wind rider" },
    { label: "黄金之躯", value: "good as gold" },
    { label: "古代活性", value: "protosynthesis" },
    { label: "夸克充能", value: "quark drive" },
    { label: "灾祸之鼎", value: "vessel of ruin" },
    { label: "灾祸之剑", value: "sword of ruin" },
    { label: "灾祸之简", value: "tablets of ruin" },
    { label: "灾祸之玉", value: "beads of ruin" },
    { label: "绯红脉动", value: "orichalcum pulse" },
    { label: "强子引擎", value: "hadron engine" },
    { label: "菌丝之力", value: "mycelium might" },
    { label: "锋锐", value: "sharpness" },
    { label: "尾甲", value: "armor tail" },
    { label: "看门犬", value: "guard dog" },
    { label: "大将", value: "supreme overlord" }
];

//属性
export const typeArray: TypeArray = [
    // { label: "所有", value: "" },
    { label: "一般", value: "normal" },
    { label: "火", value: "fire" },
    { label: "水", value: "water" },
    { label: "草", value: "grass" },
    { label: "电", value: "electric" },
    { label: "冰", value: "ice" },
    { label: "格斗", value: "fighting" },
    { label: "毒", value: "poison" },
    { label: "地面", value: "ground" },
    { label: "飞行", value: "flying" },
    { label: "超能", value: "psychic" },
    { label: "虫", value: "bug" },
    { label: "岩石", value: "rock" },
    { label: "幽灵", value: "ghost" },
    { label: "龙", value: "dragon" },
    { label: "恶", value: "dark" },
    { label: "钢", value: "steel" },
    { label: "妖精", value: "fairy" },
];

//地区
export const regionArray: RegionArray = [
    { label: "所有", value: "" },
    { label: "伽勒尔地区", value: "galar" },
    { label: "关都地区", value: "kanto" },
    { label: "城都地区", value: "johto" },
    { label: "洗翠地区", value: "hisui" },
    { label: "帕底亚地区", value: "paldean" },
    { label: "丰缘地区", value: "hoenn" },
    { label: "神奥地区", value: "sinnoh" },
    { label: "合众地区", value: "unova" },
    { label: "卡洛斯地区", value: "kalos" },
    { label: "阿罗拉地区", value: "alola" },
];